# Numpy Basics <hr style = "border: 2.5px solid#efd7a9"></hr>


Data Analyst: Hannah Lyrane P. Ibanez <br>
Department: Electrical Engineering

In [10]:
# import and packages
import numpy as np
from scipy import stats

# 1D Array

In [20]:
array_a = np.array([1,2,3])
array_a

array([1, 2, 3])

# 2D Array

In [21]:
my_array = np.array([
   [1,2,3],
   [4,5,6] 
])
my_array

array([[1, 2, 3],
       [4, 5, 6]])

In [24]:
my_array = my_array.T

In [25]:
my_array

array([[1, 4],
       [2, 5],
       [3, 6]])

In [28]:
# add by row
np.sum(my_array, axis=0)

array([ 6, 15])

In [29]:
# by column
np.sum(my_array, axis=1)

array([5, 7, 9])

# Measures of Central Tendency

In [4]:
fruits = np.array([120,60,85,150,200])
fruits

array([120,  60,  85, 150, 200])

In [ ]:
fruits_mean = np.mean(fruits)
fruits_mean

np.float64(123.0)

In [7]:
median_fruits = np.median(fruits)
median_fruits

np.float64(120.0)

In [11]:
mode_fruits = stats.mode(fruits)
mode_fruits

ModeResult(mode=np.int64(60), count=np.int64(1))

# Jaguar Vs Panther

## Jaguar

In [13]:
jaguar = np.array ([10.6,9.1,9.3,9.8,10.5,10.4,9.5,11,10.4,3,9.8])
jaguar

array([10.6,  9.1,  9.3,  9.8, 10.5, 10.4,  9.5, 11. , 10.4,  3. ,  9.8])

In [16]:
jaguar_mean = np.mean (jaguar)
jaguar_mean

np.float64(9.399999999999999)

In [31]:
median_jaguar = np.median (jaguar)
median_jaguar

np.float64(9.8)

In [32]:
mode_jaguar = stats.mode (jaguar)
mode_jaguar

ModeResult(mode=np.float64(9.8), count=np.int64(2))

In [33]:
max_jag = np.max(jaguar)
min_jag = np.min(jaguar)

range_jag = max_jag - min_jag
range_jag

np.float64(8.0)

In [41]:
#Q1
q1_jag = np.percentile(jaguar,25)
q1_jag

np.float64(9.4)

In [40]:
#Q2 (median)
q2_jag = np.percentile(jaguar,50)
q2_jag

np.float64(9.8)

In [42]:
#Q3
q3_jag = np.percentile(jaguar,75)
q3_jag

np.float64(10.45)

In [43]:
#IQR
iqr_jag = q3_jag - q1_jag
iqr_jag

np.float64(1.049999999999999)

In [44]:
# sample variance
var_jag = np.var(jaguar,ddof=1)
var_jag

np.float64(4.86)

In [46]:
# sample standard deviation
std_jag = np.std(jaguar,ddof=1)
std_jag

np.float64(2.2045407685048604)

## Panther

In [14]:
panther = np.array ([10.1,11,9.1,20,9.2,10.8,9.9,9.2,9.1,9.1])
panther

array([10.1, 11. ,  9.1, 20. ,  9.2, 10.8,  9.9,  9.2,  9.1,  9.1])

In [18]:
panther_mean = np.mean (panther)
panther_mean

np.float64(10.75)

In [47]:
panther_median = np.median (panther)
panther_median

np.float64(9.55)

In [49]:
panther_mode = stats.mode (panther)
panther_mode

ModeResult(mode=np.float64(9.1), count=np.int64(3))

In [50]:
max_panther = np.max(panther)
min_panther = np.min(panther)

range_panther = max_panther - min_panther
range_panther

np.float64(10.9)

In [51]:
q1_pan = np.percentile(panther,25)
q1_pan

np.float64(9.125)

In [52]:
q2_pan = np.percentile(panther,50)
q2_pan

np.float64(9.55)

In [53]:
q3_pan = np.percentile(panther,75)
q3_pan

np.float64(10.625)

In [54]:
iqr_pan = q3_pan - q1_pan
iqr_pan

np.float64(1.5)

In [55]:
var_pan = np.var(panther,ddof=1)
var_pan

np.float64(11.082777777777777)

In [56]:
std_pan = np.std(panther,ddof=1)
std_pan

np.float64(3.3290806204983645)